---
- name:  Creating the Sec Group
  local_action:
    module: ec2_group
    name: "{{ sec_group_name }}"
    description: sg giropops
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: SSH
    rules_egress: 
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Creating EC2 instance
  local_action: ec2
    group = {{ sec_group_name }}
    instance_type = {{ instance_type }}
    image = {{ image }}
    profile = {{ profile }} 
    wait = true
    region = {{ region }}
    keypair = {{ keypair }}
    count = {{ count }}
  register: ec2

- name: Adding instance to temp iventory
  add_host: 
    name = {{ item.public_ip }}
    groups = giropops-new
  with_items: "{{ ec2.instances }}"  

- name: Adding public ip of created instance to host file
  local_action: lineinfile
    dest = "./hosts"
    regexp = {{ item.public_ip }}
    insertafter = "[kubernetes]" 
    line = {{ item.public_ip }}
  with_items: "{{ ec2.instances }}"  

- name: Adding private ip of created instance to host file
  local_action: lineinfile
    dest = "./hosts"
    regexp = {{ item.private_ip }}
    insertafter = "[kubernetes]" 
    line = {{ item.private_ip }}
  with_items: "{{ ec2.instances }}"  

- name: Waiting the ssh 
  local_action: wait_for 
    host = {{ item.public_ip }}
    prot = 22
    state = started
  with_items: "{{ ec2.instances }}"  

- name: Adding a tag to instance
  local_action: ec2_tag
    resource = {{ item.id }} 
    region = {{ region }}
    keypair = {{ keypair }}
    profile = {{ profile }} 
    state = present
  with_items: "{{ ec2.instances }}"  
  args:
    tags:
      name: ansible-{{ item.ami_launch_index|int + 1 }}
